# Generated by Django 5.2.4 on 2025-07-09 22:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PROFORMA', 'Proforma'), ('ISSUED', 'Emitida'), ('PAID', 'Pagada'), ('OVERDUE', 'Vencida')], default='DRAFT', max_length=20)),
                ('issue_date', models.DateField(default=datetime.datetime.today, help_text='Fecha de emisión')),
                ('due_date', models.DateField(blank=True, help_text='Fecha de vencimiento', null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_irpf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('irpf_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irpf_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('irpf_tax', models.ForeignKey(help_text='El tipo de IRPF aplicado a esta línea', limit_choices_to={'tax_type': 'accounting.Tax.TaxType.IRPF'}, on_delete=django.db.models.deletion.PROTECT, related_name='irpf_tax_items', to='accounting.tax', verbose_name='IRPF')),
                ('iva_tax', models.ForeignKey(help_text='El tipo de IVA aplicado a esta línea', limit_choices_to={'tax_type': 'accounting.Tax.TaxType.IVA'}, on_delete=django.db.models.deletion.PROTECT, related_name='iva_tax_items', to='accounting.tax', verbose_name='IVA')),
            ],
        ),
    ]
