# Generated by Django 5.2.4 on 2025-07-09 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='subtotal',
            new_name='tax_base',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='subtotal',
            new_name='tax_base',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='irpf_tax',
            field=models.ForeignKey(help_text='El tipo de IRPF aplicado a esta línea', limit_choices_to={'tax_type': 'IRPF'}, on_delete=django.db.models.deletion.PROTECT, related_name='irpf_tax_items', to='accounting.tax', verbose_name='IRPF'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='iva_tax',
            field=models.ForeignKey(help_text='El tipo de IVA aplicado a esta línea', limit_choices_to={'tax_type': 'IVA'}, on_delete=django.db.models.deletion.PROTECT, related_name='iva_tax_items', to='accounting.tax', verbose_name='IVA'),
        ),
    ]
