# Generated by Django 5.2.4 on 2025-07-10 15:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('invoices', '0002_rename_subtotal_invoice_tax_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tax_base',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='tax_base',
            new_name='line_subtotal',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='total',
            new_name='line_total',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=datetime.date.today, help_text='Fecha de emisión'),
        ),
    ]
