# Generated by Django 5.2.4 on 2025-07-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='concept',
            field=models.CharField(default='Gastos de hipoteca', help_text='Concepto de la factura', max_length=255),
            preserve_default=False,
        ),
    ]
