# Generated by Django 5.2.4 on 2025-07-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Archivo PDF de la factura', null=True, upload_to='invoices/pdf'),
        ),
    ]
