# Generated by Django 5.2.4 on 2025-07-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoiceitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('RECTIFICATIVE', 'Rectificativa')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rectifies',
            field=models.ForeignKey(blank=True, help_text='Factura rectificada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectified_by', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PROFORMA', 'Proforma'), ('ISSUED', 'Emitida'), ('PAID', 'Pagada'), ('OVERDUE', 'Vencida'), ('RECTIFIED', 'Rectificada')], default='DRAFT', max_length=20),
        ),
    ]
