# Generated by Django 5.2.4 on 2025-07-09 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: IVA General 21%)', max_length=100)),
                ('tax_type', models.CharField(choices=[('IVA', 'IVA'), ('IRPF', 'IRPF')], default='IVA', help_text='Tipo de impuesto', max_length=10)),
                ('percent', models.DecimalField(decimal_places=2, help_text='Porcentaje del impuesto (ej: 21.00)', max_digits=5)),
                ('is_default', models.BooleanField(default=False, help_text='Marcar si este es el impuesto por defecto para nuevos clientes')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para desactivar un impuesto antiguo sin borrarlo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
    ]
